name: Close issues marked as fixed upon a release.
description: Close issues marked as fixed upon a release.
branding:
  icon: check-square
  color: orange
inputs:
  token:
    description: "Access token that can access and update issues."
    required: false
    default: '${{ github.token }}'
  label:
    description: "Label for bugs that should be closed upon a release"
    required: false
    default: "fixed-pending-release"
  removeLabel:
    description: "Boolean indicating whether the label should be removed from the issues."
    required: false
    default: "false"
  message:
    description: "The message to be included in a comment on the issues to be closed."
    required: false
    default: ":tada: This issue has now been fixed and is now available in the latest release! :tada:"
  isExternalRelease:
    description: "Boolean indicating whether the release is external to GitHub. If it is, no GitHub release will be found."
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
